name: Pong-Testing

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  GENERATE_DOCS: OFF
  PERFORM_TESTS: OFF

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
      with:
        cMakeVersion: 3.18.4
    - name: Install dependencies
      run: sudo apt install libgl1-mesa-dev libopenal-dev libsdl2-dev libglew-dev libglm-dev libalure-dev
    - name: Create build dir
      run: mkdir ${{github.workspace}}/build
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGENERATE_DOCS=${{env.GENERATE_DOCS}} -DPERFORM_TESTS=${{env.PERFORM_TESTS}}
    - name: Build Pong
      run: cmake --build ${{github.workspace}}/build -j 4
    - name: Packaging
      run: sudo cpack --config build/CPackConfig.cmake -B packages
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ${{github.workspace}}/packages/Pong*
